import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';

export type CounterpartyDocument = HydratedDocument<Counterparty>;

@Schema({ collection: 'counterparties', timestamps: true })
export class Counterparty {
  @Prop({ required: true, index: true })
  name!: string;

  @Prop()
  shortName?: string;

  @Prop()
  legalForm?: string;

  @Prop({ type: [String], default: [] })
  roles!: string[]; // refs by slug to CounterpartyRole

  /**
   * TZ-PARTY-301: uniqueness is per-tenant only (compound index below).
   * A global unique index would let tenant A block tenant B from adding
   * the same real counterparty.
   */
  @Prop({ required: true, index: true })
  inn!: string;

  /** TZ-PARTY-301: INN was generated by quick-create, not verified. */
  @Prop({ default: false })
  innIsStub!: boolean;

  @Prop()
  kpp?: string;

  @Prop()
  ogrn?: string;

  // Banking
  @Prop()
  bankName?: string;

  @Prop()
  bankBik?: string;

  @Prop()
  bankAccount?: string;

  @Prop()
  bankCorrAccount?: string;

  // Signer
  @Prop()
  signerName?: string;

  @Prop()
  signerPosition?: string;

  @Prop({ default: true })
  isActive!: boolean;

  @Prop({ type: [String], default: [] })
  type!: string[];

  @Prop()
  legalType?: 'ooo' | 'ip' | 'pao' | 'ao' | 'other';

  @Prop()
  website?: string;

  @Prop()
  directorName?: string;

  /** TZ-ORDERS-303: телефон для quick-create заказчика. */
  @Prop()
  phone?: string;

  /** TZ-MIG-304: корпоративная почта фирмы (отдельно от Person.email). */
  @Prop()
  email?: string;

  @Prop()
  registrationDate?: Date;

  @Prop({ type: [String], default: [] })
  partyTypes!: string[];

  @Prop({ type: [{ type: Types.ObjectId, ref: 'Photo' }], default: [] })
  photoIds!: Types.ObjectId[];

  @Prop({ type: Types.ObjectId, ref: 'Person' })
  contactPersonId?: Types.ObjectId;

  // Terms
  @Prop({ default: 10 })
  paymentTermDays!: number;

  @Prop({ default: 20 })
  vatRate!: number;

  // TZ-241: multi-tenant org scoping
  @Prop({ required: false, index: true, sparse: true })
  organizationId?: Types.ObjectId;

  @Prop({ default: false })
  isSystem!: boolean;

  /**
   * TZ-PARTY-301: soft-delete marker. Was written by `remove()` before this TZ
   * without a schema field, so strict mode silently dropped it.
   */
  @Prop({ type: Date, default: null, index: true })
  deletedAt?: Date | null;
}

export const CounterpartySchema = SchemaFactory.createForClass(Counterparty);
CounterpartySchema.index({ organizationId: 1, inn: 1 }, { unique: true, sparse: true });
