/** Auto-generated by scripts/write-build-info.mjs — do not edit manually */
export const BUILD_INFO: { readonly sha: string; readonly generatedAt: string } = {
  sha: '6d35e6db',
  generatedAt: '2026-08-28T22:53:34.656Z',
};
