/** Auto-generated by scripts/write-build-info.mjs — do not edit manually */
export const BUILD_INFO: { readonly sha: string; readonly generatedAt: string } = {
  sha: '78058065',
  generatedAt: '2026-08-24T20:48:43.762Z',
};
