/** Auto-generated by scripts/write-build-info.mjs — do not edit manually */
export const BUILD_INFO: { readonly sha: string; readonly generatedAt: string } = {
  sha: '03ad65bd',
  generatedAt: '2026-08-27T18:08:18.940Z',
};
