import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { PiStudioBlocksService, PiStudioDocumentsService, type StudioBlock, type StudioBlockLayout, type StudioDocument } from '@kppdf/data-access';
import { PiToastService } from '@kppdf/ui/toast';
import { StudioBlocksCanvasComponent } from './studio-blocks-canvas.component';
import { StudioLayersPanelComponent } from './studio-layers-panel.component';
import { StudioPropertiesPanelComponent } from './studio-properties-panel.component';
import { studioSheetRect } from './studio-geometry';

@Component({selector:'pi-studio-editor-page',standalone:true,imports:[StudioBlocksCanvasComponent,StudioLayersPanelComponent,StudioPropertiesPanelComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`@if(document();as doc){<main class="studio-shell" data-test="studio-shell"><header class="studio-ribbon"><strong>Студия документов</strong><span>{{doc.name}}</span><span class="studio-switch">Редактор</span><span>Просмотр</span></header><section class="studio-stage"><aside class="studio-rail studio-rail-left"><button type="button" (click)="addText()">Текст</button><button type="button" (click)="panel.set('layers')">Слои</button></aside><div class="studio-sheet-wrap"><div class="studio-sheet" data-test="studio-sheet" [style.width.px]="sheet().width" [style.height.px]="sheet().height" (click)="selectedId.set(null)"><pi-studio-blocks-canvas [blocks]="blocks()" [selectedId]="selectedId()" (selected)="selectedId.set($event)" (layoutChanged)="changeLayout($event.id,$event.layout)" /></div></div>@if(panel()==='layers'){<aside class="studio-panel studio-panel-left"><pi-studio-layers-panel [blocks]="blocks()" [selectedId]="selectedId()" (selected)="selectedId.set($event)" (toggleLock)="toggleLock($event)" (toggleVisible)="toggleVisible($event)" /></aside>}@if(panel()==='properties'){<aside class="studio-panel studio-panel-right"><pi-studio-properties-panel [block]="selectedBlock()" /></aside>}<aside class="studio-rail studio-rail-right"><button type="button" (click)="panel.set('properties')">Свойства</button></aside></section></main>}@else{<div>Загрузка документа…</div>}`,styles:[`:host{display:block;height:100%}.studio-shell{height:100%;display:flex;flex-direction:column;background:#eee}.studio-ribbon{height:48px;display:flex;align-items:center;gap:16px;padding:0 20px;background:#fff}.studio-stage{position:relative;flex:1;display:flex;align-items:center;justify-content:flex-end;padding:0 8px 0 64px;overflow:hidden}.studio-sheet-wrap{display:flex;align-items:center;justify-content:flex-end;width:100%;height:100%}.studio-sheet{position:relative;background:#fff;border:1px solid #d8d8d8}.studio-rail{position:absolute;z-index:4;display:flex;flex-direction:column;gap:8px}.studio-rail-left{left:12px;top:24px}.studio-rail-right{right:12px;top:24px}.studio-rail button{min-height:36px}.studio-panel{position:absolute;top:16px;bottom:16px;width:480px;z-index:3;background:#fff;border:1px solid #ddd}.studio-panel-left{left:64px}.studio-panel-right{right:64px}.studio-switch{font-weight:700;border-bottom:2px solid currentColor}`]})
export class StudioEditorPage {
 private readonly route=inject(ActivatedRoute);private readonly documents=inject(PiStudioDocumentsService);private readonly blocksService=inject(PiStudioBlocksService);private readonly toast=inject(PiToastService);private timer?:number;
 readonly document=signal<StudioDocument|null>(null);readonly blocks=signal<readonly StudioBlock[]>([]);readonly selectedId=signal<string|null>(null);readonly panel=signal<'layers'|'properties'|null>(null);readonly sheet=signal({width:0,height:0});readonly selectedBlock=signal<StudioBlock|null>(null);
 constructor(){const id=this.route.snapshot.paramMap.get('id');if(id)void firstValueFrom(this.documents.getById(id)).then(r=>{if(r.ok){this.document.set(r.data);void firstValueFrom(this.blocksService.list(id)).then(b=>{if(b.ok)this.blocks.set(b.data);});this.sheet.set(studioSheetRect(800,900,r.data.orientation));}});}
 addText():void{const d=this.document();if(!d)return;void firstValueFrom(this.blocksService.create(d._id,{expectedRevision:d.revision??1,type:'text',order:this.blocks().length,title:'Текст',content:'Новый текст',layout:{page:1,x:35,y:40,width:30,height:12,zIndex:this.blocks().length+1,rotation:0}})).then(r=>{if(r.ok){this.blocks.update(b=>[...b,r.data]);this.document.update(x=>x?{...x,revision:(x.revision??1)+1}:x);}else this.conflict();});}
 changeLayout(id:string,layout:StudioBlockLayout):void{this.blocks.update(b=>b.map(x=>x._id===id?{...x,layout}:x));this.schedule();}
 toggleLock(block:StudioBlock):void{this.blocks.update(b=>b.map(x=>x._id===block._id?{...x,locked:!x.locked}:x));this.schedule();}
 toggleVisible(block:StudioBlock):void{this.blocks.update(b=>b.map(x=>x._id===block._id?{...x,isActive:x.isActive===false}:x));this.schedule();}
 private schedule():void{if(this.timer)clearTimeout(this.timer);this.timer=window.setTimeout(()=>this.save(),400);}
 private save():void{const d=this.document();if(!d)return;const updates=this.blocks().filter((b):b is StudioBlock&{layout:StudioBlockLayout}=>Boolean(b.layout)).map(b=>({blockId:b._id,layout:b.layout}));void firstValueFrom(this.blocksService.updateLayouts(d._id,{expectedRevision:d.revision??1,updates})).then(r=>{if(r.ok){this.blocks.set(r.data);this.document.update(x=>x?{...x,revision:(x.revision??1)+1}:x);}else this.conflict();});}
 private conflict():void{this.toast.error('Документ изменён в другом месте');const id=this.document()?._id;if(id)void firstValueFrom(this.documents.getById(id)).then(r=>{if(r.ok){this.document.set(r.data);void firstValueFrom(this.blocksService.list(id)).then(b=>{if(b.ok)this.blocks.set(b.data);});}});}
}
